### PR TITLE
Hotfix Terms of Use

### PR DESCRIPTION
**Pull request by monkeymantra**
Soundtrack of this PR: [Rock Master Scott & the Dynamic Three - The Roof Is On Fire](https://www.youtube.com/watch?v=-Vv_LwwwpmU)

### Motivation

There were mistakes in our terms of use

### In this PR

The new Terms of Use file

### CODE REVIEW

**Review by sugargoat — CHANGES_REQUESTED** [review]
Want to double check if this should be to develop or main? I think I accidentally pushed to main earlier with some README changes, and we may want to clean up on develop and do a merge to main

**Comment by BrianCorbin** [comment]
> Want to double check if this should be to develop or main? I think I accidentally pushed to main earlier with some README changes, and we may want to clean up on develop and do a merge to main

So, for hotfixes, I believe it should be directly to main

**Comment by BrianCorbin** [comment]
If we're following git flow procedure. It should be a direct commit to main, and after a direct commit (or rebase from main) to develop.

**Review by BrianCorbin — APPROVED** [review]

**Comment by sugargoat** [comment]
Amazing - thank you @BrianCorbin !

**Review by sugargoat — APPROVED** [review]

**Comment by jcape** [comment]
The MD5sum of this doesn't match the one in mobilecoin.git
```
$ curl https://github.com/mobilecoinofficial/mobot/blob/dd82a6123ffb0e6da6a75f53f313a396d28c9b15/TERMS-OF-USE.md | md5sum
2bb653a81817103dc4594e8931781af7  -
md5sum TERMS-OF-USE.md 
6fc7a4a7a21915add9f36fd20da4e8d3  TERMS-OF-USE.md
```

**Comment by jcape** [comment]
> 
> 
> The MD5sum of this doesn't match the one in mobilecoin.git
> 
> ```
> $ curl https://raw.githubusercontent.com/mobilecoinofficial/mobot/dd82a6123ffb0e6da6a75f53f313a396d28c9b15/TERMS-OF-USE.md | md5sum
> 868ef37ea75c11134736483581331992  -
> $ md5sum TERMS-OF-USE.md 
> 6fc7a4a7a21915add9f36fd20da4e8d3  TERMS-OF-USE.md
> ```

Looks like this is a missing newline at the end of file, its' fine.

**Pull request merged**
